name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: ["find-twin"] # Список приложений

    steps:
      - uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config --global user.email "zenkovich_so@mail.ru"
          git config --global user.name "sergey-cyber"

      - name: Install dependencies
        run: |
          cd ${{ matrix.app }}
          npm ci

      - name: Build application
        run: |
          cd ${{ matrix.app }}
          npm run build

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd ${{ matrix.app }}
          npx gh-pages -d dist -b gh-pages -o origin -r "https://github.com/sergey-cyber/dev-space-games" -p "/${{ matrix.app }}"
