name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: ["find-twin"] # Список приложений

    steps:
      - uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config --global user.name "sergey-cyber"
          git config --global user.email "zenkovich_so@mail.ru"
          git remote set-url origin https://x-access-token:${{ secrets.DEPLOY_GH_PAGES }}@github.com/$GITHUB_REPOSITORY

      - name: Install dependencies
        run: |
          cd ${{ matrix.app }}
          npm ci

      - name: Build application
        run: |
          cd ${{ matrix.app }}
          npm run build

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.DEPLOY_GH_PAGES }}
        run: |
          cd ${{ matrix.app }}
          npx gh-pages -d dist -b gh-pages -r origin -c "${GITHUB_REPOSITORY}" -p "/${{ matrix.app }}"
